version: "3"
services:

  database:
    image: mysql
    container_name: database
    ports:
      - "4000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234

  core:
    build:
      context: .
      dockerfile: core.Dockerfile
    container_name: core
    restart: always
    ports:
      - "3000:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/sys
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234

  front:
    build:
      context: ./src/front
      dockerfile: front.Dockerfile
    container_name: front
    ports:
    - '4200:4200'
    command: bash -c "npm install && ng serve --host 0.0.0.0 --port 4200 --prod "
