
spring:
  datasource:
    url: jdbc:mysql://localhost:4000/sys
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect

  liquibase:
    enabled: false