spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:default
    username: alexis
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true