spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demospring
    username: root
    password: Alexis241096
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
