package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CustomerRepository customerRepository;

    @GetMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser (@RequestParam (required = false,defaultValue="World") String name
            , @RequestParam(required = false,defaultValue="World") String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Customer n = new Customer();
        n.setName(name);
        n.setEmail(email);
        customerRepository.save(n);
        return "Saved";
    }
    @GetMapping(path="/all")
    public String getAllUsers(Model model) {
        // This returns a JSON or XML with the users
        Iterable<Customer> customers = customerRepository.findAll();
        model.addAttribute("customers",customers);
        return "demo/all";

    }
}
